live_config_reload = true

import = [
    "~/.config/alacritty/themes/themes/challenger_deep.toml"
]

[font]
size = 16

[font.normal]
family = "Monaspace Neon"
style = "Regular"

[window]
decorations = "Buttonless"
dynamic_padding = true
dynamic_title = true
opacity = 1.0

[window.padding]
x = 10
y = 10


